// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 系统基础信息
type SystemInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`                                             // 操作系统 "Ubuntu 22.04 LTS"
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                                 // 主机名 "web-server-01"
	CpuModel      string                 `protobuf:"bytes,3,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`                 // CPU型号 "Intel Core i7-9700K"
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`                                         // 架构 "x86_64"
	LoadAvg       string                 `protobuf:"bytes,5,opt,name=load_avg,json=loadAvg,proto3" json:"load_avg,omitempty"`                    // 系统负载 "0.45, 0.32, 0.28"
	UptimeSeconds uint64                 `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"` // 运行时间（秒）
	CpuCores      uint32                 `protobuf:"varint,7,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`                // CPU 核心数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_internal_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *SystemInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfo) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *SystemInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *SystemInfo) GetLoadAvg() string {
	if x != nil {
		return x.LoadAvg
	}
	return ""
}

func (x *SystemInfo) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemInfo) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

// CPU 指标
type CPUMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsagePercent  float64                `protobuf:"fixed64,1,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"` // CPU 使用率 0-100
	CoreCount     uint32                 `protobuf:"varint,2,opt,name=core_count,json=coreCount,proto3" json:"core_count,omitempty"`           // 核心数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUMetrics) Reset() {
	*x = CPUMetrics{}
	mi := &file_internal_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUMetrics) ProtoMessage() {}

func (x *CPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUMetrics.ProtoReflect.Descriptor instead.
func (*CPUMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *CPUMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

func (x *CPUMetrics) GetCoreCount() uint32 {
	if x != nil {
		return x.CoreCount
	}
	return 0
}

// 内存指标
type MemoryMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RamUsedBytes   uint64                 `protobuf:"varint,1,opt,name=ram_used_bytes,json=ramUsedBytes,proto3" json:"ram_used_bytes,omitempty"`       // RAM 已使用字节数
	RamTotalBytes  uint64                 `protobuf:"varint,2,opt,name=ram_total_bytes,json=ramTotalBytes,proto3" json:"ram_total_bytes,omitempty"`    // RAM 总字节数
	SwapUsedBytes  uint64                 `protobuf:"varint,3,opt,name=swap_used_bytes,json=swapUsedBytes,proto3" json:"swap_used_bytes,omitempty"`    // Swap 已使用字节数
	SwapTotalBytes uint64                 `protobuf:"varint,4,opt,name=swap_total_bytes,json=swapTotalBytes,proto3" json:"swap_total_bytes,omitempty"` // Swap 总字节数
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_internal_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryMetrics) GetRamUsedBytes() uint64 {
	if x != nil {
		return x.RamUsedBytes
	}
	return 0
}

func (x *MemoryMetrics) GetRamTotalBytes() uint64 {
	if x != nil {
		return x.RamTotalBytes
	}
	return 0
}

func (x *MemoryMetrics) GetSwapUsedBytes() uint64 {
	if x != nil {
		return x.SwapUsedBytes
	}
	return 0
}

func (x *MemoryMetrics) GetSwapTotalBytes() uint64 {
	if x != nil {
		return x.SwapTotalBytes
	}
	return 0
}

// 网络指标
type NetworkMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BytesRecvPerSec uint64                 `protobuf:"varint,1,opt,name=bytes_recv_per_sec,json=bytesRecvPerSec,proto3" json:"bytes_recv_per_sec,omitempty"` // 接收速率 字节/秒
	BytesSentPerSec uint64                 `protobuf:"varint,2,opt,name=bytes_sent_per_sec,json=bytesSentPerSec,proto3" json:"bytes_sent_per_sec,omitempty"` // 发送速率 字节/秒
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_internal_proto_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkMetrics) GetBytesRecvPerSec() uint64 {
	if x != nil {
		return x.BytesRecvPerSec
	}
	return 0
}

func (x *NetworkMetrics) GetBytesSentPerSec() uint64 {
	if x != nil {
		return x.BytesSentPerSec
	}
	return 0
}

// 单个磁盘指标
type DiskMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`  // 挂载点 "/" 或 "/home"
	UsedBytes     uint64                 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`    // 已使用字节数
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"` // 总字节数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_internal_proto_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *DiskMetrics) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskMetrics) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DiskMetrics) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

// 完整的系统指标数据
type SystemMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SystemInfo       *SystemInfo            `protobuf:"bytes,1,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`                       // 系统信息
	Cpu              *CPUMetrics            `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`                                                       // CPU 指标
	Memory           *MemoryMetrics         `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`                                                 // 内存指标
	Network          *NetworkMetrics        `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`                                               // 网络指标
	Disks            []*DiskMetrics         `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`                                                   // 磁盘列表
	Timestamp        int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                          // 时间戳（Unix 秒）
	DiskTotalPercent float64                `protobuf:"fixed64,7,opt,name=disk_total_percent,json=diskTotalPercent,proto3" json:"disk_total_percent,omitempty"` // 磁盘总使用率 0-100
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_internal_proto_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_internal_proto_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *SystemMetrics) GetSystemInfo() *SystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *SystemMetrics) GetCpu() *CPUMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemMetrics) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemMetrics) GetNetwork() *NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *SystemMetrics) GetDisks() []*DiskMetrics {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *SystemMetrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SystemMetrics) GetDiskTotalPercent() float64 {
	if x != nil {
		return x.DiskTotalPercent
	}
	return 0
}

var File_internal_proto_metrics_proto protoreflect.FileDescriptor

const file_internal_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/metrics.proto\x12\amonitor\"\xc8\x01\n" +
	"\n" +
	"SystemInfo\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\tcpu_model\x18\x03 \x01(\tR\bcpuModel\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x19\n" +
	"\bload_avg\x18\x05 \x01(\tR\aloadAvg\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x04R\ruptimeSeconds\x12\x1b\n" +
	"\tcpu_cores\x18\a \x01(\rR\bcpuCores\"P\n" +
	"\n" +
	"CPUMetrics\x12#\n" +
	"\rusage_percent\x18\x01 \x01(\x01R\fusagePercent\x12\x1d\n" +
	"\n" +
	"core_count\x18\x02 \x01(\rR\tcoreCount\"\xaf\x01\n" +
	"\rMemoryMetrics\x12$\n" +
	"\x0eram_used_bytes\x18\x01 \x01(\x04R\framUsedBytes\x12&\n" +
	"\x0fram_total_bytes\x18\x02 \x01(\x04R\rramTotalBytes\x12&\n" +
	"\x0fswap_used_bytes\x18\x03 \x01(\x04R\rswapUsedBytes\x12(\n" +
	"\x10swap_total_bytes\x18\x04 \x01(\x04R\x0eswapTotalBytes\"j\n" +
	"\x0eNetworkMetrics\x12+\n" +
	"\x12bytes_recv_per_sec\x18\x01 \x01(\x04R\x0fbytesRecvPerSec\x12+\n" +
	"\x12bytes_sent_per_sec\x18\x02 \x01(\x04R\x0fbytesSentPerSec\"n\n" +
	"\vDiskMetrics\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\"\xc7\x02\n" +
	"\rSystemMetrics\x124\n" +
	"\vsystem_info\x18\x01 \x01(\v2\x13.monitor.SystemInfoR\n" +
	"systemInfo\x12%\n" +
	"\x03cpu\x18\x02 \x01(\v2\x13.monitor.CPUMetricsR\x03cpu\x12.\n" +
	"\x06memory\x18\x03 \x01(\v2\x16.monitor.MemoryMetricsR\x06memory\x121\n" +
	"\anetwork\x18\x04 \x01(\v2\x17.monitor.NetworkMetricsR\anetwork\x12*\n" +
	"\x05disks\x18\x05 \x03(\v2\x14.monitor.DiskMetricsR\x05disks\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12,\n" +
	"\x12disk_total_percent\x18\a \x01(\x01R\x10diskTotalPercentB0Z.github.com/easyssh/server/internal/proto;protob\x06proto3"

var (
	file_internal_proto_metrics_proto_rawDescOnce sync.Once
	file_internal_proto_metrics_proto_rawDescData []byte
)

func file_internal_proto_metrics_proto_rawDescGZIP() []byte {
	file_internal_proto_metrics_proto_rawDescOnce.Do(func() {
		file_internal_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_metrics_proto_rawDesc), len(file_internal_proto_metrics_proto_rawDesc)))
	})
	return file_internal_proto_metrics_proto_rawDescData
}

var file_internal_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_metrics_proto_goTypes = []any{
	(*SystemInfo)(nil),     // 0: monitor.SystemInfo
	(*CPUMetrics)(nil),     // 1: monitor.CPUMetrics
	(*MemoryMetrics)(nil),  // 2: monitor.MemoryMetrics
	(*NetworkMetrics)(nil), // 3: monitor.NetworkMetrics
	(*DiskMetrics)(nil),    // 4: monitor.DiskMetrics
	(*SystemMetrics)(nil),  // 5: monitor.SystemMetrics
}
var file_internal_proto_metrics_proto_depIdxs = []int32{
	0, // 0: monitor.SystemMetrics.system_info:type_name -> monitor.SystemInfo
	1, // 1: monitor.SystemMetrics.cpu:type_name -> monitor.CPUMetrics
	2, // 2: monitor.SystemMetrics.memory:type_name -> monitor.MemoryMetrics
	3, // 3: monitor.SystemMetrics.network:type_name -> monitor.NetworkMetrics
	4, // 4: monitor.SystemMetrics.disks:type_name -> monitor.DiskMetrics
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_proto_metrics_proto_init() }
func file_internal_proto_metrics_proto_init() {
	if File_internal_proto_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_metrics_proto_rawDesc), len(file_internal_proto_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_metrics_proto_goTypes,
		DependencyIndexes: file_internal_proto_metrics_proto_depIdxs,
		MessageInfos:      file_internal_proto_metrics_proto_msgTypes,
	}.Build()
	File_internal_proto_metrics_proto = out.File
	file_internal_proto_metrics_proto_goTypes = nil
	file_internal_proto_metrics_proto_depIdxs = nil
}
