// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../web/src/app/dashboard/ai-assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ai-assistant">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/ai-assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/automation/batch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/automation/batch">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/automation/batch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/automation/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/automation/history">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/automation/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/automation/schedules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/automation/schedules">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/automation/schedules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/logs/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/logs/login">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/logs/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/logs">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/monitoring/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/monitoring/alerts">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/monitoring/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/monitoring/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/monitoring/health">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/monitoring/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/monitoring/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/monitoring/resources">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/monitoring/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/scripts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/scripts">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/scripts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/servers/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/servers/history">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/servers/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/servers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/servers">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/servers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/settings/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/integrations">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/settings/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/settings/management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/management">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/settings/management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/settings/security-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/security-center">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/settings/security-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/settings/system-config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings/system-config">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/settings/system-config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/sftp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/sftp">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/sftp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/storage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/storage">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/storage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/terminal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/terminal">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/terminal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/terminal/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/terminal/sessions">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/terminal/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/transfers/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/transfers/history">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/transfers/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/dashboard/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../web/src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../web/src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup">> = Specific
  const handler = {} as typeof import("../../../web/src/app/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../web/src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../web/src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../web/src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../web/src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
