// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Clear(before: string): $CancellablePromise<number> {
    return $Call.ByID(3753844377, before);
}

export function GetById(id: string): $CancellablePromise<$models.DesktopActivityLogItem> {
    return $Call.ByID(880276824, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetStatistics(params: $models.DesktopActivityLogListParams): $CancellablePromise<$models.DesktopActivityLogStatistics> {
    return $Call.ByID(1294758251, params).then(($result: any) => {
        return $$createType1($result);
    });
}

export function List(params: $models.DesktopActivityLogListParams): $CancellablePromise<$models.DesktopActivityLogListResult> {
    return $Call.ByID(2580650124, params).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Record(input: $models.DesktopActivityLogRecordInput): $CancellablePromise<$models.DesktopActivityLogItem> {
    return $Call.ByID(211165969, input).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DesktopActivityLogItem.createFrom;
const $$createType1 = $models.DesktopActivityLogStatistics.createFrom;
const $$createType2 = $models.DesktopActivityLogListResult.createFrom;
