// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export type DesktopCapability = string;

export class DesktopRuntimeInfo {
    "profile": string;
    "version": string;
    "platform": string;
    "arch": string;
    "dataDir": string;
    "capabilities": { [_ in DesktopCapability]?: boolean };

    /** Creates a new DesktopRuntimeInfo instance. */
    constructor($$source: Partial<DesktopRuntimeInfo> = {}) {
        if (!("profile" in $$source)) {
            this["profile"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("platform" in $$source)) {
            this["platform"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("dataDir" in $$source)) {
            this["dataDir"] = "";
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopRuntimeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopRuntimeInfo {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField5_0($$parsedSource["capabilities"]);
        }
        return new DesktopRuntimeInfo($$parsedSource as Partial<DesktopRuntimeInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
